export const styles = [
  { value: "feminine", label: "Feminine" },
  { value: "masculine", label: "Masculine" },
  { value: "traditional", label: "Traditional" },
  { value: "realism", label: "Realism" },
  { value: "watercolour", label: "Watercolour" },
  { value: "blackwork", label: "Blackwork" },
  { value: "dotwork", label: "Dotwork" },
  { value: "ornamental", label: "Ornamental" },
  { value: "geometric", label: "Geometric" },
  { value: "neo-traditional", label: "Neo Traditional" },
  { value: "japanese", label: "Japanese" },
  { value: "chinese", label: "Chinese" },
  { value: "tribal", label: "Tribal" },
  { value: "polynesian", label: "Polynesian" },
  { value: "maori", label: "Maori" },
  { value: "celtic", label: "Celtic" },
  { value: "biomechanical", label: "Biomechanical" },
  { value: "surrialism", label: "Surrialism" },
  { value: "abstract", label: "Abstract" },
  { value: "illustrative", label: "Illustrative" },
  { value: "minimalist", label: "Minimalist" },
  { value: "fine-line", label: "Fine Line" },
  { value: "chrome-effect", label: "Chrome Effect" },
  { value: "trash-polka", label: "Trash Polka" },
  { value: "black-and-grey", label: "Black and Grey" },
  { value: "lettering", label: "Lettering" },
  { value: "calligraphy", label: "Calligraphy" },
  { value: "graffiti", label: "Graffiti" },
  { value: "neo-japanese", label: "Neo Japanese" },
  { value: "new-school", label: "New School" },
  { value: "chicano", label: "Chicano" },
  { value: "mandala", label: "Mandala" },
  { value: "pointillism", label: "Pointillism" },
  { value: "comic-book-style", label: "Comic Book Style" },
  { value: "large-scale", label: "Large Scale" },
  { value: "engraved/wood-cut", label: "Engraved/Wood Cut" },
  { value: "glitch-tattoos", label: "Glitch Tattoos" },
  { value: "disney", label: "Disney" },
  { value: "nordic", label: "Nordic" },
];

export const genders = [
    { value: "male",label:'Male' },
    {value:'female',label:'Female'},
    {value:'non-binary',label:'Non-Binary'},
    {value:'other',label:'Other'},
    {value:'prefer-not-to-say',label:'Prefer not to say'}
];


export const tattooThemes = [
    {value:'nature',label:'Nature'},
    {value:'animals',label:'Animals'},
    {value:'fantasy',label:'Fantasy'},
    {value:'skulls-and-skeletons',label:'Skulls and Skeletons'},
    {value:'tribal',label:'Tribal'},
    {value:'mythology',label:'Mythology'},
    {value:'celestial',label:'Celestial'},
    {value:'religious',label:'Religious'},
    {value:'portraits',label:'Portraits'},
    {value:'pop-culture',label:'Pop Culture'},
    {value:'music',label:'Music'},
    {value:'travel',label:'Travel'},
    {value:'quotes-and-text',label:'Quotes and Text'},
    {value:'abstract',label:'Abstract'},
    {value:'sci-fi',label:'Sci-Fi'},
    {value:'vintage',label:'Vintage'},
    {value:'steampunk',label:'Steampunk'},
    {value:'sports',label:'Sports'},
    {value:'horoscope-and-zodiac',label:'Horoscope and Zodiac'},
    {value:'food-and-drink',label:'Food and Drink'},
    {value:'love-and-relationships',label:'Love and Relationships'},
    {value:'political-and-social-statements',label:'Political and Social Statements'},
    {value:'mandalas',label:'Mandalas'},
]

export const Type = [
    {value:'stick-and-poke',label:'Stick and Poke'},
    {value:'tattoo-gun',label:'Tattoo Machine'},
    {value:'bamboo',label:'Bamboo'},
    {value:'scar-cover-up',label:'Scar Cover Up'},
    {value:'mastectomy',label:'Mastectomy'},
    {value:'work-from-a-vegan-studio',label:'Work from a Vegan Studio'},
    {value:'work-from-a-feminist-studio',label:'Work from a Feminist Studio'},
    {value:'person-of-colour-artist',label:'Person of Colour Artist'},
    {value:'work-from-a-poc-owned-studio',label:'Work from a POC Owned Studio'},
    {value:'guest-artist',label:'Guest Artist'},
    {value:'work-from-an-all-female-studio',label:'Work From an All-Female Studio'},
    {value:'lgbtq+-artist',label:'LGBTQ+ Artist'},
    {value:'work-from-a-lgbtq+-owned-studio',label:'Work from a LGBTQ+ Owned Studio'},
    {value:'sustainable-tattooing',label:'Sustainable Tattooing'},
    {value:'cremation-tattoos',label:'Cremation Tattoos'},
    {value:'mobile-tattoo-unit',label:'Mobile Tattoo Unit'},
]
