services:
  app:
    build: .
    container_name: inkformed
    depends_on:
      - db
    environment:
      - DATABASE=mongodb://root:CO4Am0h0P7nZWYFcjgo8YPEOA87n8qKPA1OdXf92cDc9EK5UI54UPKBLFSCfkIgN@159.65.167.67:27017/inkformed
      - PORT=8282
  db:
    image: mongo
    container_name: inkformedMongoDB
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
volumes:
  db-data:
